# Deep Learning A Z Classificação Mais Classes - Iris simples

In [1]:
# !pip install tensorflow===2.16.1

In [3]:
# Importando as bibliotecas
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

2026-02-11 10:55:17.927667: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-11 10:55:18.583337: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-11 10:55:21.899830: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [4]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('3.0.0', '2.4.2', '2.20.0', '1.8.0')

In [5]:
# Importa o tipo de modelo mais comum uma pilha linear de camadas
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense #Importa a camada "Densa", que é a camada neural básica onde 
from tensorflow.keras import utils as np_utils# Importa utilitários do Keras como o to_categorical para converter 
from sklearn.preprocessing import LabelEncoder# Ferramenta do Scikit-Learn para converter rótulos em formato de texto 
from sklearn.model_selection import train_test_split# Função crucial para dividir seu conjunto de dados: uma parte para o 
from sklearn.metrics import confusion_matrix

In [6]:
base = pd.read_csv('/home/Ront/Documentos/Card-14/Seção 5/iris.csv') 
base

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [11]:
X = base.iloc[:, 0:4].values # Atributos previsores 150 linhas e 4 colunas
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
y = base.iloc[:, 4].values # Atributos classe 150 linhas e 1 coluna
y

<StringArray>
[   'Iris-setosa',    'Iris-setosa',    'Iris-setosa',    'Iris-setosa',
    'Iris-setosa',    'Iris-setosa',    'Iris-setosa',    'Iris-setosa',
    'Iris-setosa',    'Iris-setosa',
 ...
 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
 'Iris-virginica', 'Iris-virginica']
Length: 150, dtype: str

In [13]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y) #transforma as labels em números
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
y.shape

(150,)

In [15]:
y = np_utils.to_categorical(y) # Transforma os valores de y em categorias 
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [16]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

In [17]:
X_treinamento.shape, X_teste.shape

((112, 4), (38, 4))

In [18]:
y_treinamento.shape, y_teste.shape

((112, 3), (38, 3))

In [23]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (4,)), # Camada de entrada com 4 neurônios
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units = 3, activation = 'softmax')
    ])

In [24]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
# Função de perda e métricas
rede_neural.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])

In [26]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - categorical_accuracy: 0.3214 - loss: 1.5058
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3304 - loss: 1.4187 
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3393 - loss: 1.3626 
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3393 - loss: 1.3153 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.3393 - loss: 1.2813 
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3393 - loss: 1.2518 
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3393 - loss: 1.2284 
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3393 - loss: 1.2086 
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3393 - loss: 1.1933 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3304 - loss: 1.1791 
Epoch 11/1

In [27]:
rede_neural.evaluate(X_teste, y_teste) # Avalia o modelo com os dados

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - categorical_accuracy: 1.0000 - loss: 0.0232 


[0.02316703461110592, 1.0]

In [28]:
previsoes = rede_neural.predict(X_teste) # Faz as previsões com os dados de teste
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
[[1.8419185e-12 1.7865060e-04 9.9982142e-01]
 [1.6360370e-03 9.8759991e-01 1.0764132e-02]
 [4.5810705e-10 3.1959007e-03 9.9680406e-01]
 [1.6360370e-03 9.8759991e-01 1.0764132e-02]
 [9.9997610e-01 5.4611128e-06 1.8377181e-05]
 [5.1675127e-12 3.0643411e-04 9.9969357e-01]
 [9.9997884e-01 4.6485661e-06 1.6442638e-05]
 [9.9999052e-01 1.6026609e-06 7.8820831e-06]
 [3.4185797e-07 9.7039394e-02 9.0296024e-01]
 [1.6360370e-03 9.8759991e-01 1.0764132e-02]
 [9.9999708e-01 3.0060193e-07 2.4817855e-06]
 [5.5209704e-04 9.6564102e-01 3.3806898e-02]
 [9.9995321e-01 1.3102928e-05 3.3629429e-05]
 [1.5846819e-03 9.8727560e-01 1.1139698e-02]
 [5.8757601e-04 9.6769696e-01 3.1715538e-02]
 [1.6360370e-03 9.8759991e-01 1.0764132e-02]
 [7.0019650e-12 3.5920669e-04 9.9964088e-01]
 [3.9130905e-16 2.3149239e-06 9.9999768e-01]
 [1.6360370e-03 9.8759991e-01 1.0764132e-02]
 [9.9999875e-01 8.7128690e-08 1.0553632e-06]
 [1.6360370e-03 9.8759991e-01 1.0764132e-02]
 [2.0993251e-04 9

In [29]:
previsoes = previsoes > 0.5
print(previsoes)

[[False False  True]
 [False  True False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]]


In [30]:
y_teste2 = [np.argmax(t) for t in y_teste] # Retorna o índice do valor True em cada linha
print(y_teste2)

[np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(2), np.int64(0), np.int64(0), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(2), np.int64(0), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(0), np.int64(2), np.int64(0), np.int64(0), np.int64(2)]


In [31]:
previsoes2 = [np.argmax(t) for t in previsoes]
print(previsoes2)

[np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(2), np.int64(0), np.int64(0), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(2), np.int64(0), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(0), np.int64(2), np.int64(0), np.int64(0), np.int64(2)]


In [32]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy_score(y_teste2, previsoes2)

1.0

In [35]:
confusion_matrix(y_teste2, previsoes2)

array([[11,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 15]])