In [1]:
# biblioteca torch
import torch

In [4]:
# criando um tensor 5x2 com valores decimais
x = torch.tensor([[1.5, 2.5], [3.5, 4.5], [5.5, 6.5], [7.5, 8.5], [9.5, 10.5]])
print(x)
print("Shape original:", x.shape)

tensor([[ 1.5000,  2.5000],
        [ 3.5000,  4.5000],
        [ 5.5000,  6.5000],
        [ 7.5000,  8.5000],
        [ 9.5000, 10.5000]])
Shape original: torch.Size([5, 2])


In [7]:
# multiplicando por um valor decimal e somando um valor inteiro
print(x * 0.5)
print(x.add(100))

tensor([[0.7500, 1.2500],
        [1.7500, 2.2500],
        [2.7500, 3.2500],
        [3.7500, 4.2500],
        [4.7500, 5.2500]])
tensor([[101.5000, 102.5000],
        [103.5000, 104.5000],
        [105.5000, 106.5000],
        [107.5000, 108.5000],
        [109.5000, 110.5000]])


In [8]:
# mudando o formato com view para 2 linhas e 5 colunas
print("\nview(2, 5):\n", x.view(2, 5))


view(2, 5):
 tensor([[ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000],
        [ 6.5000,  7.5000,  8.5000,  9.5000, 10.5000]])


In [10]:
# criando tensor com dimensões extras para testar
a = torch.ones(1, 5, 1, 2)
print(a.shape)
print(a.squeeze().shape)
print(a.squeeze(0).shape)

torch.Size([1, 5, 1, 2])
torch.Size([5, 2])
torch.Size([5, 1, 2])


In [14]:
# criando matriz y que combine com o shape de x
y = torch.tensor([[2, 1, 0],
                  [0, 1, 2]], dtype=torch.float)
resultado = torch.matmul(x, y)
print(resultado)
print(resultado.shape)

tensor([[ 3.,  4.,  5.],
        [ 7.,  8.,  9.],
        [11., 12., 13.],
        [15., 16., 17.],
        [19., 20., 21.]])
torch.Size([5, 3])


In [17]:
# testando concatenação em eixos diferentes
b = torch.randn(3, 2)
cat_dim0 = torch.cat([b, b], dim=0)
cat_dim1 = torch.cat([b, b], dim=1)
print(b.shape)
print(cat_dim0.shape)
print(cat_dim1.shape)

torch.Size([3, 2])
torch.Size([6, 2])
torch.Size([3, 4])


In [18]:
# invertendo a ordem dos eixos
c = torch.randn(2, 10, 5)
print(c.shape)
print(c.permute(2, 0, 1).shape)

torch.Size([2, 10, 5])
torch.Size([5, 2, 10])
