In [13]:
# biblioteca torch
import torch

In [3]:
# crie um tensor 3x4
x = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Tensor x:\n", x)
print("Shape:", x.shape)

Tensor x:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Shape: torch.Size([3, 4])


In [5]:
# operações basicas
print("\nx * 2:\n", x * 2)
print("\nx + 5:\n", x.add(5))


x * 2:
 tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

x + 5:
 tensor([[ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17]])


In [6]:
# reshape com view
print("\nview(6, 2):\n", x.view(6, 2))
print("\nview(12, 1):\n", x.view(12, 1))


view(6, 2):
 tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

view(12, 1):
 tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])


In [7]:
# squeezer removendo dimensão
a = torch.ones(3, 1, 4)
print("\nShape antes do squeeze:", a.shape)
print("Shape depois do squeeze:", a.squeeze(1).shape)


Shape antes do squeeze: torch.Size([3, 1, 4])
Shape depois do squeeze: torch.Size([3, 4])


In [9]:
# multiplicação de matrizes
y = torch.tensor([[1,0],[0,1],[1,0],[0,1]])
resultado = torch.matmul(x, y)
print("\nmatmul(x, y):\n", resultado)
print("Shape do resultado:", resultado.shape)


matmul(x, y):
 tensor([[ 4,  6],
        [12, 14],
        [20, 22]])
Shape do resultado: torch.Size([3, 2])


In [11]:
# concatenação
b = torch.randn(2, 3, 5)
cat_axis1 = torch.cat([b, b], axis=1)
cat_axis2 = torch.cat([b, b], axis=2)
print("\nShape original:", b.shape)
print("cat axis=1:", cat_axis1.shape)
print("cat axis=2:", cat_axis2.shape)


Shape original: torch.Size([2, 3, 5])
cat axis=1: torch.Size([2, 6, 5])
cat axis=2: torch.Size([2, 3, 10])


In [12]:
# permute
c = torch.randn(2, 5, 3)
print("\nShape original:", c.shape)
print("permute(2,0,1):", c.permute(2, 0, 1).shape)
print("permute(1,2,0):", c.permute(1, 2, 0).shape)


Shape original: torch.Size([2, 5, 3])
permute(2,0,1): torch.Size([3, 2, 5])
permute(1,2,0): torch.Size([5, 3, 2])
