In [1]:
import numpy as np  # Importa a biblioteca NumPy com o apelido 'np' comummente usado assim o apelido

In [2]:
lista = [1, 2, 3]  # Cria uma lista comum em Python com três elementos

In [3]:
lista

[1, 2, 3]

In [4]:
np.array(lista) #converti a minha lista numa array de python
# Arrays NumPy permitem realizar operações matemáticas de forma mais eficiente e rápida do que listas comuns

array([1, 2, 3])

In [5]:
Matriz = [1 , 2 , 3], [4, 5, 6] , [7, 8, 9]

In [6]:
np.array(Matriz) #Essa matriz resultando suas linhas depende da quantidade de conchetes

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Metados de Numpy

In [8]:
# np.arange cria um array com valores numéricos em sequência (como um range do Python, mas retorna array)
np.arange(0, 10)  # Cria um array de 0 até 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# np.arange pode receber um terceiro argumento: o passo
np.arange(0, 10, 2)  # Cria um array de 0 até 8, pulando de 2 em 2

array([0, 2, 4, 6, 8])

In [10]:
# np.zeros cria um array só com zeros; np.ones, só com uns
np.zeros(10)  # Array com 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [13]:
arr = np.zeros((5, 5))

In [14]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# np.eye cria uma matriz identidade (1s na diagonal principal)
np.eye(3)  # Matriz 3x3 com 1s na diagonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# np.linspace cria um array com N valores igualmente espaçados entre um intervalo
np.linspace(0, 1, 5)  # De 0 a 1, com 5 números igualmente espaçados

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [19]:
# np.random.rand cria arrays com números aleatórios entre 0 e 1
np.random.rand(2, 3)  # Matriz 2x3 com valores aleatórios

array([[0.6293931 , 0.56289695, 0.75779875],
       [0.1857059 , 0.81209623, 0.26915091]])

In [20]:
# np.random.randn gera valores aleatórios com distribuição normal (média 0, desvio padrão 1)
np.random.randn(2, 3)

array([[-1.353629  , -1.8216871 ,  0.66871229],
       [ 0.69465747,  0.30723721,  1.03633616]])

In [21]:
# np.random.randint gera números inteiros aleatórios dentro de um intervalo
np.random.randint(1, 100, 5)  # Gera 5 números inteiros aleatórios entre 1 e 99

array([ 1, 21, 61, 67, 30])

In [22]:
arr = np.random.rand(25)  # Cria um array com 25 números aleatórios entre 0 e 1, com distribuição uniforme

In [23]:
arr  # Exibe o array criado

array([0.14281447, 0.05256428, 0.99961535, 0.42819983, 0.64120191,
       0.18540131, 0.84123049, 0.79201971, 0.93913945, 0.88535934,
       0.65498625, 0.57709143, 0.82750314, 0.92329042, 0.62637554,
       0.70490196, 0.27762008, 0.57105456, 0.31256885, 0.47106636,
       0.65256521, 0.11284259, 0.9059086 , 0.79565534, 0.37863079])

In [24]:
arr.reshape((5, 5))  # Reorganiza o array em uma matriz 5x5 (5 linhas, 5 colunas)

array([[0.14281447, 0.05256428, 0.99961535, 0.42819983, 0.64120191],
       [0.18540131, 0.84123049, 0.79201971, 0.93913945, 0.88535934],
       [0.65498625, 0.57709143, 0.82750314, 0.92329042, 0.62637554],
       [0.70490196, 0.27762008, 0.57105456, 0.31256885, 0.47106636],
       [0.65256521, 0.11284259, 0.9059086 , 0.79565534, 0.37863079]])

In [25]:
arr.shape  # Mostra o formato (shape) atual do array, ou seja, quantos elementos ele tem em cada dimensão

(25,)

In [26]:
arr.max()  # Mostra a função que retorna o maior valor do array

np.float64(0.9996153452668747)

In [27]:
arr.min()  # Mostra a função que retorna o menor valor do array

np.float64(0.052564277436283)

In [28]:
arr.argmax()  # Mostra a função que retorna o índice do maior valor do array

np.int64(2)

In [29]:
arr.argmin()  # Mostra a função que retorna o índice do menor valor do array

np.int64(1)

In [30]:
# Fatiamento de arrays

In [31]:
arr = np.arange(0, 30, 3)  # Cria um array com números de 0 até 30 (exclusivo), pulando de 3 em 3

In [32]:
arr  # Exibe o array: [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [33]:
arr[3]  # Mostra o elemento na posição 3 (índice começa do zero), que é o número 9

np.int64(9)

In [34]:
np.int64(9)  # Converte o número 9 em tipo np.int64 explicitamente (não muda nada visivelmente aqui)

np.int64(9)

In [35]:
arr[:5]  # Fatiamento: mostra os cinco primeiros elementos do array

array([ 0,  3,  6,  9, 12])

In [36]:
arr[::3]  # Pega de 3 em 3 elementos (step 3): do começo ao fim, pulando 3 posições

array([ 0,  9, 18, 27])

In [37]:
arr[2] = 100  # Modifica o valor da posição 2 (antes era 6, agora é 100)

In [38]:
arr  # Exibe o array atualizado com o valor 100 na posição 2

array([  0,   3, 100,   9,  12,  15,  18,  21,  24,  27])

In [39]:
arr = np.arange(30).reshape(5, 6)  # Cria um array de 0 a 29 e reorganiza como uma matriz de 5 linhas e 6 colunas

In [40]:
arr  # Exibe a nova matriz 5x6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [41]:
arr.shape  # Mostra o formato (shape) da matriz, que é (5, 6)

(5, 6)

In [42]:
arr[3]  # Mostra a quarta linha inteira da matriz (índice 3)

array([18, 19, 20, 21, 22, 23])

In [43]:
arr2 = arr[3]  # Cria uma nova variável `arr2` que aponta para a mesma linha (não é cópia!)

In [44]:
arr2[2] = 100  # Altera um valor em `arr2`, o que também altera a matriz original (por ser referência)

In [45]:
arr2 = arr[3].copy()  # Com isso sim cria uma cópia real da linha, independente do original

In [46]:
arr[1:4, 3:]  # Fatiamento da matriz: pega as linhas 1 até 3 (exclusivo do 4), e colunas da 3 em diante

array([[ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [47]:
arr > 50 #caso for maior que 50 é verdadeiro

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [48]:
bol = arr > 50  # Cria um array booleano cada elemento será True se for maior que 50, False caso contrário

In [49]:
arr[bol]  # Filtra os valores do array onde a condição (maior que 50) é verdadeira

array([100])

In [50]:
array = np.linspace(0, 100, 30)  # Cria um array com 30 valores igualmente espaçados entre 0 e 100

In [51]:
array.shape  # Mostra o formato do array: (30,), ou seja, um array unidimensional com 30 elementos

(30,)

In [52]:
array = array.reshape(3, 10) #ele gera 

In [53]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [54]:
array[0:2, 2]  # Acessa a terceira coluna (índice 2) das duas primeiras linhas (índices 0 e 1)

array([ 6.89655172, 41.37931034])

In [55]:
#Operaçoes

In [56]:
arr = np.arange(0, 16) # Cria um array arr com números de 0 a 15.

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
arr + arr # Soma elemento por elemento (ex: 0+0, 1+1, 2+2...).

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [59]:
arr - arr # Subtrai elemento por elemento, o que resulta em um array cheio de zeros.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
arr * arr #Multiplicação elemento a elemento: faz o quadrado de cada número

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [61]:
arr / arr # Aqui ocorre um aviso de erro (RuntimeWarning), pois o primeiro elemento é 0/0, que é indefinido (nan). Os demais valores são 1

/tmp/ipykernel_5920/1151289972.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr # Aqui ocorre um aviso de erro (RuntimeWarning), pois o primeiro elemento é 0/0, que é indefinido (nan). Os demais valores são 1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [62]:
1 / arr # Outro aviso de erro, agora por divisão por zero no primeiro elemento (1/0). O resto são os inversos dos números seguintes.

/tmp/ipykernel_5920/1979364493.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # Outro aviso de erro, agora por divisão por zero no primeiro elemento (1/0). O resto são os inversos dos números seguintes.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [63]:
arr ** 2 # Eleva cada número ao quadrado, igual ao arr * arr.

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [64]:
arr + 100 # Soma 100 a cada elemento do array (vetor + escalar).

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [65]:
arr - 100 # Subtrai 100 de cada elemento.

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [66]:
arr * 100 # Multiplica cada elemento por 100.

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [67]:
np.log(arr) # tentativa de calcular logaritmo natural. Como log(0) não existe, dá RuntimeWarning e retorna -inf no primeiro elemento.

/tmp/ipykernel_5920/2374451285.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # tentativa de calcular logaritmo natural. Como log(0) não existe, dá RuntimeWarning e retorna -inf no primeiro elemento.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ])

In [68]:
np.exp(arr) # Calcula a exponencial de cada valor no array. Como os valores são grandes, o resultado cresce rapidamente (exponencial).

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [69]:
np.std(arr) # Calcula o desvio padrão dos valores em arr, uma medida de dispersão.

np.float64(4.6097722286464435)

In [70]:
np.sin(arr) # Calcula o seno de cada valor em arr (em radianos).

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [71]:
np.max(arr) # Retorna o maior valor do array, que é 15.

np.int64(15)

In [72]:
np.min(arr) # Retorna o menor valor do array, que é 0.

np.int64(0)

In [73]:
arr.max()

np.int64(15)

In [74]:
arr.min()

np.int64(0)

In [75]:
# Pandas - Series

In [76]:
import pandas as pd  # Importa a biblioteca pandas e atribui o apelido 'pd' (convenção comum)

In [77]:
labels = ['a', 'b', 'c']  # Cria uma lista com rótulos personalizados para usar como índice

In [78]:
minha_lista = [10, 20, 30]  # Cria uma lista de valores inteiros
arr = np.array([10, 20, 30])  # Converte a lista para um array NumPy
d = {'a': 10, 'b': 20, 'c': 30}  # Cria um dicionário com rótulos como chaves e valores inteiros

In [79]:
pd.Series(data=minha_lista, index=labels)

a    10
b    20
c    30
dtype: int64

In [80]:
pd.Series(data=minha_lista, index=labels)  # Cria uma Series com os valores da lista e os rótulos definidos

a    10
b    20
c    30
dtype: int64

In [81]:
series = pd.Series(data=minha_lista, index=labels)  # Armazena a Series na variável 'series' para uso posterior

In [82]:
pd.Series(minha_lista, labels)

a    10
b    20
c    30
dtype: int64

In [83]:
serie1 = pd.Series([1, 2, 3, 4], index=["EUA", "Alemanha", "USS", "Japão"]) # Cria uma Series chamada 'serie1' com valores de 1 a 4 e índices personalizados com nomes de países

In [84]:
serie1  # Exibe o conteúdo de 'serie1'

EUA         1
Alemanha    2
USS         3
Japão       4
dtype: int64

In [85]:
serie2 = pd.Series([1, 2, 3, 4], index=["EUA", "Alemanha", "Italia", "Japão"])  
# Cria outra Series chamada 'serie2', com os mesmos valores mas índices ligeiramente diferentes ('Italia' no lugar de 'USS')

In [86]:
serie2

EUA         1
Alemanha    2
Italia      3
Japão       4
dtype: int64

In [87]:
serie1 + serie2  
# Soma as duas Series elemento a elemento, alinhando pelos índices:
# - Onde os índices coincidem (EUA, Alemanha, Japão), os valores são somados.
# - Onde os índices não coincidem (USS em serie1, Italia em serie2), o resultado é NaN.

Alemanha    4.0
EUA         2.0
Italia      NaN
Japão       8.0
USS         NaN
dtype: float64

In [88]:
# Data frame - fatiamento

In [89]:
np.random.seed(101)

In [90]:
df = pd.DataFrame(np.random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())

In [91]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [92]:
df[['W', 'Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [93]:
 df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [94]:
df['new'] = df['W'] + df['X']

In [95]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [96]:
df.drop('new', axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [97]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [98]:
df = df.drop('new', axis=1)

In [99]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [100]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [101]:
df.loc[['A', 'B'], ['X', 'Y', 'Z']]

X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [102]:
df.iloc[1:4, 2:]

Y         Z
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

In [103]:
# DataFrame - Seleção condicional

In [104]:
np.random.seed(101)

In [105]:
df = pd.DataFrame(np.random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())

In [106]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [107]:
boll = df > 0

In [108]:
df[boll]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [109]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [110]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [111]:
bol = df['W']>0
df2 = df[boll]
df2['Y']

A    0.907969
B         NaN
C    0.528813
D         NaN
E    2.605967
Name: Y, dtype: float64

In [112]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [113]:
df[(df['W']>0) | (df['Y'] > 1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [114]:
df.reset_index(inplace=True)

In [115]:
col = 'RS MG SP SC AM'.split()

In [116]:
df['Estados'] = col

In [117]:
df.set_index('Estados', inplace=True)

In [118]:
df

index         W         X         Y         Z
Estados                                              
RS          A  2.706850  0.628133  0.907969  0.503826
MG          B  0.651118 -0.319318 -0.848077  0.605965
SP          C -2.018168  0.740122  0.528813 -0.589001
SC          D  0.188695 -0.758872 -0.933237  0.955057
AM          E  0.190794  1.978757  2.605967  0.683509

In [119]:
# DataFrame - Índices Multiníveis

In [120]:
outside = ['G1','G1','G1','G2','G2','G3']
inside = [1,2,3,1,2,1]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [121]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G3']

In [122]:
inside

[1, 2, 3, 1, 2, 1]

In [123]:
hier_index = list(zip(outside,inside))

In [124]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G3', 1)]

In [125]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [126]:
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B'])

In [127]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
G3 1  0.638787  0.329646

In [128]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [129]:
df.loc['G1'].loc(1)

In [130]:
df.index.names = ['Grupo', 'Numero']

In [131]:
df

A         B
Grupo Numero                    
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
G3    1       0.638787  0.329646

In [132]:
df.xs('G1')

A         B
Numero                    
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [133]:
df.xs(1, level='Numero')

A         B
Grupo                    
G1     0.302665  1.693723
G2     0.166905  0.184502
G3     0.638787  0.329646

In [134]:
# DataFrame -  Dados Ausentes

In [135]:
d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]}

In [136]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [137]:
df = pd.DataFrame(d)

In [138]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [139]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [140]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [141]:
df.fillna(value='vazio')

A      B  C
0    1.0    5.0  1
1    2.0  vazio  2
2  vazio  vazio  3

In [142]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [143]:
df.fillna(method='ffill')

/tmp/ipykernel_5920/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [144]:
# DataFrame -  GroupBy

In [145]:
data = {'empresa':['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
        'Nome':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Venda':[200,120,340,124,243,350]}

In [146]:
df = pd.DataFrame(data)

In [147]:
df

empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [148]:
grup = df.groupby('empresa')

In [149]:
grup

In [150]:
grup.sum()

Nome  Venda
empresa                   
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [151]:
grup.describe()

Venda                                                        
        count   mean         std    min     25%    50%     75%    max
empresa                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [152]:
grup = df.groupby('Nome')

In [153]:
# DataFrame - Concatenar, Juntar e Mesclar

In [154]:
#ele explico a respeito 

In [155]:
# DataFrame - Operações

In [156]:
# Lista Python normal - lenta
lista = [1, 2, 3, 4, 5]
nova_lista = [x * 2 for x in lista]  # Precisa de loop

In [157]:
# Array NumPy - rápido  
array = np.array([1, 2, 3, 4, 5])
novo_array = array * 2  # Operação direta, sem loop

In [158]:
array = np.arange(30).reshape(5, 6)

In [159]:
array[array > 5]  # Pega só os valores maiores que 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29])

In [160]:
dados = {
    'nome': ['Alice', 'Bruno', 'Carla'],
    'idade': [30, 25, 28],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']
}

In [161]:
df = pd.DataFrame(dados)

In [162]:
df.to_csv('dados.csv')# Lê arquivo CSV

In [163]:
df.head()# Mostra as primeiras linhas

nome  idade          cidade
0  Alice     30       São Paulo
1  Bruno     25  Rio de Janeiro
2  Carla     28  Belo Horizonte

In [164]:
df.info()# Resumo dos dados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   nome    3 non-null      object
 1   idade   3 non-null      int64 
 2   cidade  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [165]:
df = pd.DataFrame({
    'nome': ['Alice', 'Bruno', 'Carla', 'Daniel', 'Eva'],
    'idade': [30, 17, 28, 15, 22],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba', 'Fortaleza']
})

In [166]:
df['nome'] # Uma coluna específica

0     Alice
1     Bruno
2     Carla
3    Daniel
4       Eva
Name: nome, dtype: object

In [167]:
df[['cidade', 'idade']] # Várias colunas

cidade  idade
0       São Paulo     30
1  Rio de Janeiro     17
2  Belo Horizonte     28
3        Curitiba     15
4       Fortaleza     22

In [168]:
df[df['idade'] > 18] 

nome  idade          cidade
0  Alice     30       São Paulo
2  Carla     28  Belo Horizonte
4    Eva     22       Fortaleza

In [169]:
df = pd.DataFrame({
    'nome': ['Alice', 'Bruno', 'Carla', 'Alice', 'Bruno', 'Eva'],
    'idade': [30, 17, 28, 30, 17, 22],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'São Paulo', 'Rio de Janeiro', 'Fortaleza']
})

In [170]:
df.describe()  # Estatísticas básicas de tudo

idade
count   6.000000
mean   24.000000
std     6.164414
min    17.000000
25%    18.250000
50%    25.000000
75%    29.500000
max    30.000000

In [171]:
df['idade'].value_counts()  # Conta quantas vezes cada valor aparece

idade
30    2
17    2
28    1
22    1
Name: count, dtype: int64

In [172]:
df = pd.DataFrame({
    'categoria': ['A', 'B', 'A', 'B', 'A'],
    'vendas': [100, 200, 300, 400, 500],
    'estoque': [10, 20, 30, 40, 50]
})

In [173]:
df.groupby('categoria').mean()  # Média por categoria

vendas  estoque
categoria                 
A           300.0     30.0
B           300.0     30.0

In [174]:
df.groupby('categoria')['vendas'].sum()  # Total de vendas por cidade

categoria
A    900
B    600
Name: vendas, dtype: int64

In [175]:
df = pd.DataFrame({
    'nome': ['Alice', 'Bruno', 'Carla'],
    'idade': [25, None, 30]
})

In [176]:
df.isnull() # Mostra onde tem dado faltando

nome  idade
0  False  False
1  False   True
2  False  False

In [177]:
df.dropna() # Remove linhas com dados faltando

nome  idade
0  Alice   25.0
2  Carla   30.0

In [178]:
df.fillna(0) # Preenche com zero onde está faltando

nome  idade
0  Alice   25.0
1  Bruno    0.0
2  Carla   30.0

In [ ]:
np.zeros(5) # Array de zeros: [0. 0. 0. 0. 0.]

In [ ]:
np.ones(3) # Array de uns: [1. 1. 1.]

In [ ]:
np.arange(0, 10) # Sequência: [0 1 2 3 4 5 6 7 8 9]

In [ ]:
S

In [ ]:
np.zeros((3, 4)) # Matriz 3x4 de zeros

In [ ]:
np.eye(3) # Matriz identidade 3x3

In [ ]:
np.random.rand(3)     # 3 números aleatórios entre 0 e 1

In [ ]:
np.random.randint(0, 10, 5)  # 5 números inteiros entre 0 e 9

In [ ]:
S

In [180]:
arr = np.arange(0, 10)

In [185]:
arr[2] # Elemento na posição 2

np.int64(2)

In [182]:
arr[2:5] # Elementos da posição 2 até 4

array([2, 3, 4])

In [183]:
arr[arr > 5]  # Todos elementos maiores que 5

array([6, 7, 8, 9])

In [186]:
dados = np.array([1, 5, 3, 8, 2, 9])

In [ ]:
# Pegar só os números pares

In [187]:
pares = dados[dados % 2 == 0]  # [8, 2]

In [189]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [190]:
a + b # [5, 7, 9]

array([5, 7, 9])

In [191]:
a * b    # [4, 10, 18]

array([ 4, 10, 18])

In [192]:
a ** 2   # [1, 4, 9]

array([1, 4, 9])

In [193]:
# Com escalares
a * 10   # [10, 20, 30]

array([10, 20, 30])

In [194]:
dados = np.random.rand(100)

In [195]:
dados.mean() # Média

np.float64(0.4856770154970958)

In [196]:
dados.std() # Desvio padrão

np.float64(0.2770212714729233)

In [197]:
dados.max() # Máximo

np.float64(0.9873127505313937)

In [198]:
dados.min() # Mínimo

np.float64(0.013241011086396526)

In [199]:
dados.sum() # Soma total

np.float64(48.56770154970958)

In [ ]:
# Criando Series

In [200]:
vendas = pd.Series([100, 200, 300], index=['Jan', 'Fev', 'Mar'])

In [201]:
print(vendas['Jan'])  # 100

100


In [ ]:
# Operações com Series

In [202]:
vendas * 1.1  # Aumentar 10%

Jan    110.0
Fev    220.0
Mar    330.0
dtype: float64

In [203]:
vendas[vendas > 150]  # Filtrar valores

Fev    200
Mar    300
dtype: int64

In [ ]:
# Criando DataFrame

In [236]:
dados = {
    'nome': ['Ana', 'João', 'Maria'],
    'idade': [25, 30, 28],
    'Salario': [5000, 6000, 5500]
}

In [237]:
df = pd.DataFrame(dados)

In [238]:
print(df.columns.tolist())  # Ver todas as colunas

['nome', 'idade', 'Salario']


In [239]:
# Selecionar colunas
df['nome']  

0      Ana
1     João
2    Maria
Name: nome, dtype: object

In [240]:
df[['nome', 'idade']] # Múltiplas colunas

nome  idade
0    Ana     25
1   João     30
2  Maria     28

In [241]:
# Selecionar linhas
df.loc[0] # Primeira linha

nome        Ana
idade        25
Salario    5000
Name: 0, dtype: object

In [242]:
df.iloc[0:2] # Primeiras duas linhas

nome  idade  Salario
0   Ana     25     5000
1  João     30     6000

In [243]:
# Filtros condicionais
df[df['idade'] > 25]  # Pessoas com mais de 25 anos

nome  idade  Salario
1   João     30     6000
2  Maria     28     5500

In [244]:
df[df['Salario'] > 5000]  # Com acento

nome  idade  Salario
1   João     30     6000
2  Maria     28     5500

In [247]:
df.describe() # Estatísticas gerais

idade  Salario
count   3.000000      3.0
mean   27.666667   5500.0
std     2.516611    500.0
min    25.000000   5000.0
25%    26.500000   5250.0
50%    28.000000   5500.0
75%    29.000000   5750.0
max    30.000000   6000.0

In [248]:
df['Salario'].mean() # Média de salários

np.float64(5500.0)

In [250]:
df.info() # Informações sobre os dados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   nome     3 non-null      object
 1   idade    3 non-null      int64 
 2   Salario  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


In [251]:
df.head()           # Primeiras 5 linhas

nome  idade  Salario
0    Ana     25     5000
1   João     30     6000
2  Maria     28     5500

In [255]:
# Dados de vendas por região
vendas = pd.DataFrame({
    'Região': ['Norte', 'Sul', 'Norte', 'Sul'],
    'Vendas': [100, 200, 150, 300],
    'Produto': ['A', 'B', 'A', 'B']
})

In [256]:
# Agrupar por região
vendas.groupby('Região')['Vendas'].sum()

Região
Norte    250
Sul      500
Name: Vendas, dtype: int64

In [257]:
# Dados com valores faltando
df_com_nan = pd.DataFrame({
    'A': [1, 2, np.nan],
    'B': [5, np.nan, np.nan],
    'C': [1, 2, 3]
})

In [258]:
# Remover linhas com NaN
df_com_nan.dropna()

A    B  C
0  1.0  5.0  1

In [259]:
# Preencher NaN com um valor
df_com_nan.fillna(0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [260]:
# Preencher com a média
df_com_nan['A'].fillna(df_com_nan['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

    Nome  Idade  Salario
0    Ana     25     5000
1   João     30     6000
2  Maria     28     5500


In [268]:
# Ler arquivos
df = pd.read_csv('dados.csv')

In [270]:
# Salvar arquivos
df.to_csv('resultado.csv', index=False)

In [273]:
# No Jupyter Notebook
import pandas as pd
import numpy as np

In [ ]:
# Carregar dados
df = pd.read_csv('vendas.csv')

In [ ]:
# Usar NumPy para cálculos estatísticos
media_vendas = np.mean(df['vendas'])
desvio_vendas = np.std(df['vendas'])