In [1]:
# biblioteca para trabalhar com tensores
import torch

In [15]:
# criando uma matriz 2x4
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
x.shape

torch.Size([2, 4])

In [16]:
# multiplica tods os elementos por 10
x * 10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [17]:
# soma 10 a cada elemento
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [19]:
# printa o X
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [20]:
x.shape

torch.Size([2, 4])

In [18]:
# reorganiza os 8 elementos em 4 linhas e 2 colunas
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [21]:
# estica tudo em uma única coluna
x.view(8,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [22]:
# cria um tensor preenchido com 1
a = torch.ones(2,1,10)
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [10]:
print(f"Esta é a forma (shape) antes de aplicar o squeeze: {a.shape}")
squeezed = a.squeeze(1)
print(f"Esta é a forma (shape) depois de aplicar o squeeze: {squeezed.shape}")


Esta é a forma (shape) antes de aplicar o squeeze: torch.Size([2, 1, 10])
Esta é a forma (shape) depois de aplicar o squeeze: torch.Size([2, 10])


In [23]:
# tem 2 linhas e 4 colunas
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
# criando a matriz Y
y = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

In [25]:
# multiplicação de matrizes
torch.matmul(x,y)

tensor([[ 70,  80,  90],
        [158, 184, 210]])

In [13]:
x = torch.randn(1,4,5)
z = torch.cat([x,x], axis = 1)
print('Concatenated axis 1:', x.shape, z.shape)

Concatenated axis 1: torch.Size([1, 4, 5]) torch.Size([1, 8, 5])


In [14]:
x = torch.randn(3,20,10)
z = x.permute(2,0,1)
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([3, 20, 10]) torch.Size([10, 3, 20])
