# Deep Learning A Z Classificação binária - Brest Cancer simples
Base de dados: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

In [2]:
import pandas as pd # Biblioteca padrão do Pandas

In [3]:
pd.__version__ # Confirmando a versão

'3.0.0'

In [6]:
# previsores
x = pd.read_csv('/home/Ront/Documentos/Card-14/Seção 4/entradas_breast.csv') #importando o arquivo de entradas
x
#importando o arquivo de entradas

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [7]:
# classes
y = pd.read_csv('/home/Ront/Documentos/Card-14/Seção 4/saidas_breast.csv')  #importando o arquivo de saida
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [6]:
import sklearn # Importando a biblioteca sklearn
from sklearn.model_selection import train_test_split # a função que será usada para dividir os dados em conjuntos de treinamento e teste.

In [8]:
sklearn.__version__ # Confirmando a versao}

'1.8.0'

In [9]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, Y, test_size=0.25) # divide os dados em 4 conjuntos

In [10]:
X_treinamento.shape, y_treinamento.shape #Verifica as dimensões dos conjuntos de treinamento

((426, 30), (426, 1))

In [12]:
X_teste.shape # Verifica as dimensões do conjunto de teste

(143, 30)

In [13]:
import tensorflow as tf # Importando a biblioteca TensorFlow
from tensorflow.keras.models import Sequential #importando a classe Sequential do módulo models

2026-02-06 13:43:24.417508: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-06 13:43:25.375838: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-06 13:43:28.563542: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [14]:
tf.__version__ # Confirmando a versão

'2.20.0'

In [15]:
#criando uma instância da classe Sequential
rede_neural = Sequential([

  tf.keras.layers.InputLayer(shape = (30,)), # Define que a rede receberá 30 atributos colunas de entrada
  tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),  # Camada oculta com 16 neurônio função ReLU e pesos iniciais aleatórios
  tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),  # Camada oculta com 16 neurônio função ReLU e pesos iniciais aleatórios
  tf.keras.layers.Dense(units = 1, activation = 'sigmoid')# Camada de saída com 1 neurônio e função Sigmoid ideal para classificação binária
])

2026-02-06 13:43:53.426514: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [18]:
30 * 16, 496 - 480 # Bias

(480, 16)

In [19]:
496 + 17

513

In [16]:
rede_neural.summary() # Resumo da rede neural

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
426 / 10

42.6

In [17]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5) # Define o otimizador Adam com uma taxa de aprendizado de 0.001

In [20]:
# Configura o treinamento do modelo
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy']) #

In [22]:
# Inicia o treinamento da rede neural
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.6432 - loss: 0.9826
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6808 - loss: 0.5590
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7582 - loss: 0.5054
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7606 - loss: 0.6097
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8052 - loss: 0.5037
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8169 - loss: 0.5274
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8099 - loss: 0.4751
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8239 - loss: 0.4884
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7934 - loss: 0.5903
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.3840
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8451 -

In [36]:
pesos0 = rede_neural.layers[0].get_weights() # Obtém os pesos da primeira camada oculta
pesos0

[array([[-2.50282679e-02, -2.68826276e-01, -5.48671074e-02,
         -1.61379657e-03, -1.29520774e-01,  6.66917488e-02,
         -2.94991553e-01,  3.82594675e-01, -1.29165566e-02,
          5.72405420e-02, -4.64918278e-02, -2.73521185e-01,
          1.52721226e-01,  2.65561014e-01, -3.22231203e-02,
          4.77533229e-02],
        [-9.23376903e-03, -3.01043153e-01, -3.72668393e-02,
         -2.66034137e-02, -1.58828646e-02,  1.76246613e-01,
         -1.93580061e-01,  1.68864921e-01,  1.79944988e-02,
          8.88444185e-02, -7.56867975e-03, -2.67098516e-01,
          7.84070045e-02,  1.91217273e-01, -1.38863567e-02,
         -3.21599692e-02],
        [ 7.69790113e-02, -1.33785913e-02, -2.54241982e-03,
         -2.70026494e-02, -1.00121163e-01, -6.92133680e-02,
         -1.84270486e-01,  2.39211723e-01,  9.94131938e-02,
          1.49644673e-01,  6.17409870e-03, -1.61216900e-01,
          2.16878489e-01,  1.93688527e-01, -2.02488545e-02,
         -2.54329741e-02],
        [-2.0245593

In [37]:
len(pesos0) # Verifica o tamanho da lista de pesos

2

In [38]:
len(pesos0[1]) # Verifica o tamanho da matriz de pesos da primeira camada oculta 1

16

In [39]:
len (pesos0[0]) # Verifica o tamanho da matriz de pesos da primeira camada oculta 0

30

In [40]:
peso1 = rede_neural.layers[1].get_weights() # Obtém os pesos da segunda camada oculta
peso1

[array([[ 7.71030858e-02, -3.43224227e-01, -1.69676542e-02,
          9.14228186e-02,  2.29328889e-02, -1.51490301e-01,
          1.16838189e-02,  1.06333382e-02,  2.05128893e-01,
          9.00040418e-02, -2.48663872e-02, -1.34278089e-02,
         -1.19396463e-01,  1.27667515e-02,  2.29364075e-02,
         -7.56249623e-03],
        [ 1.29030526e-01,  3.22654359e-02,  3.53451702e-03,
          2.27507353e-01, -3.85034643e-02,  1.48391416e-02,
         -1.61404181e-02, -1.39597375e-02,  3.37153941e-01,
          1.81820199e-01, -4.73143309e-02, -2.65185386e-02,
         -1.54165596e-01, -7.13024065e-02, -6.84915259e-02,
          1.88362375e-02],
        [-3.22217532e-02, -1.75488219e-02, -3.37605253e-02,
         -1.55394962e-02,  4.23004217e-02, -3.21634077e-02,
          4.15067747e-03,  4.39751633e-02,  1.11749666e-02,
         -4.47305851e-02,  4.63238135e-02, -2.98457630e-02,
         -1.77714322e-02,  2.13029096e-03, -2.91407779e-02,
          1.92501897e-03],
        [-7.4957914

In [41]:
pesos2 = rede_neural.layers[2].get_weights() # Obtém os pesos da camada de saída
pesos2

[array([[ 0.02986449],
        [ 0.1972423 ],
        [-0.4710977 ],
        [ 0.02668962],
        [-0.44092268],
        [ 0.10678151],
        [-0.2079277 ],
        [-0.27270508],
        [ 0.08347095],
        [ 0.06189379],
        [-0.36910695],
        [ 0.02391979],
        [-0.6433648 ],
        [-0.4598661 ],
        [-0.5178699 ],
        [ 0.08151482]], dtype=float32),
 array([0.17497456], dtype=float32)]

In [23]:
previsoes = rede_neural.predict(X_teste) # Previsões da rede neural
previsoes = previsoes > 0.5 # Transformação das previsões em valores binários (True ou False)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


In [24]:
previsoes # As previsões

array([[ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [25]:
y_teste

0
34   0
28   0
253  0
241  1
384  1
..  ..
568  1
403  1
402  1
524  1
472  1

[143 rows x 1 columns]

In [27]:
import sklearn # Importando a biblioteca sklearn
from sklearn.model_selection import train_test_split # a função que será usada para dividir os dados em conjuntos de treinamento e teste.

In [30]:
accuracy_score(y_teste, previsoes)

0.5244755244755245

In [31]:
confusion_matrix(y_teste, previsoes)

array([[20, 37],
       [31, 55]])

In [32]:
48 + 80, 9 + 6

(128, 15)

In [33]:
128 / 143, 15 / 143

(0.8951048951048951, 0.1048951048951049)

In [35]:
rede_neural.evaluate(X_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.8741 - loss: 0.4309  


[0.4308668375015259, 0.8741258978843689]