In [2]:
# Install TensorFlow
# !pip install -q tensorflow-gpu==2.0.0-beta1

#try:
#    %tensorflow_version 2.x  # Colab only.
# except Exception:
#    pass

import tensorflow as tf
print(tf.__version__)

2.20.0


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [4]:
# just a simple test
sentences = [
    'I like eggs and ham.',
    'I love chocolate and bunnies.',
    'I hate onions.'
]

In [5]:
MAX_VOCAB_SIZE = 20000 # tamanho máximo
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE) # cria um tokenizador com o maximo
tokenizer.fit_on_texts(sentences) # remove espaços
sequences = tokenizer.texts_to_sequences(sentences) # converte as sentenças em sequencias de números

In [7]:
# mostrando que o indice começa em 0 mais o 0 é reservado para o padding
print(sequences)

[[1, 3, 4, 2, 5], [1, 6, 7, 2, 8], [1, 9, 10]]


In [8]:
tokenizer.word_index # Mostra o índice de cada palavra

{'i': 1,
 'and': 2,
 'like': 3,
 'eggs': 4,
 'ham': 5,
 'love': 6,
 'chocolate': 7,
 'bunnies': 8,
 'hate': 9,
 'onions': 10}

In [9]:
data = pad_sequences(sequences) # realiza o padding das sequências
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [10]:
MAX_SEQUENCE_LENGTH = 5 # limitando para 5 palavras 
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [11]:
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post') # padding no final  
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 1  9 10  0  0]]


In [12]:
data = pad_sequences(sequences, maxlen=6) # padding com 6 de tamanho
print(data)

[[ 0  1  3  4  2  5]
 [ 0  1  6  7  2  8]
 [ 0  0  0  1  9 10]]


In [14]:
data = pad_sequences(sequences, maxlen=4) # aqui diminuímos o tamanho da sequência
print(data)

[[ 3  4  2  5]
 [ 6  7  2  8]
 [ 0  1  9 10]]


In [15]:
data = pad_sequences(sequences, maxlen=4, truncating='post') # truncando no final
print(data)

[[ 1  3  4  2]
 [ 1  6  7  2]
 [ 0  1  9 10]]
